[project]
name = 'Galactic-Ecosystem-Generator'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.alien-species-nft]
path = 'contracts/alien-species-nft.clar'
clarity_version = 2
epoch = 2.5

[contracts.quantum-evolution]
path = 'contracts/quantum-evolution.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
